# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationTestDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_region', models.CharField(help_text=b'brain region', max_length=100)),
                ('cell_type', models.CharField(help_text=b'brain region', max_length=100)),
                ('data_location', models.CharField(help_text=b'location of comparison data', max_length=200)),
                ('data_type', models.CharField(help_text=b'type of comparison data (number, histogram, time series, etc.)', max_length=100)),
                ('data_modality', models.CharField(help_text=b'recording modality for comparison data (ephys, fMRI, 2-photon, etc)', max_length=100)),
                ('test_type', models.CharField(help_text=b'single cell activity, network structure or network activity', max_length=100)),
                ('protocol', models.TextField(blank=True, help_text=b'Description of the experimental protocol')),
                ('code_location', models.CharField(help_text=b'location of the code that defines the test', max_length=200)),
                ('author', models.CharField(help_text=b'Author of this test', max_length=100)),
            ],
        ),
    ]
