# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_search_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtestdefinition',
            name='name',
            field=models.CharField(blank=True, help_text=b'short descriptive name', max_length=200),
        ),
        migrations.AlterField(
            model_name='validationtestdefinition',
            name='cell_type',
            field=models.CharField(help_text=b'cell type', max_length=100),
        ),
    ]
