# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_search_api', '0003_auto_20161219_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtestdefinition',
            name='species',
            field=models.CharField(default='mouse', help_text=b'species', max_length=100),
            preserve_default=False,
        ),
    ]
